### ISSUE TITLE
PPM on Redhat 7

### ISSUE THREAD

**Issue by GitHubUser4234** [ltb-project/ppm#13]
Hi,

I'm referring to https://www.mail-archive.com/ltb-dev@lists.ltb-project.org/msg01450.html where it says that there might be a Redhat-packing for PPM. Is this available on Redhat 7 now simply using yum? Thanks!

**Comment by coudot** [comment]
Packages are provided in https://github.com/ltb-project/openldap-rpm

See https://ltb-project.org/documentation/openldap-rpm

**Comment by GitHubUser4234** [comment]
Thanks :)

**Comment by davidcoutadeur** [comment]
For clarifying:
- ppm is not available for Redhat "official" OpenLDAP package,
- ppm is available through OpenLDAP LTB repository (so you must install OpenLDAP LTB package)
- OpenLDAP package won't be maintained by Red-Hat at long term. They are pushing forward their own implementation Red-Hat Directory Server.
- ppm is not compatible with Red-Hat Directory Server
