### ISSUE TITLE
ppm not working with ldapadd command

### ISSUE THREAD

**Issue by ahmad-zul** [ltb-project/ppm#15]
I have a question, is ppm can work using ldapadd command? 
I tested with ldappasswd and it works like a charm.
ldappasswd -x -H ldap://localhost:389 -D "uid=testuser@gmail.com,ou=people,dc=user,dc=test,dc=com" -w abc123 -s lol

but with ldapadd command, it still adding user that does not conform to password policy.
ldapadd -H ldap://localhost:389 -D cn=admin,dc=user,dc=test,dc=com -w admin -f to-test/06-ai-people.ldif

and my ldif file is:
dn: uid=testuser@gmail.com,ou=people,dc=user,dc=test,dc=com
uid: testuser@gmail.com
objectclass: inetOrgPerson
userPassword: abc123
sn: Smith
cn: testuser@gmail.com
givenName: James
o: mss

My ppm.conf is:
minQuality 3
maxLength 0
checkRDN 1
maxConsecutivePerClass 0
useCracklib 0
class-upperCase ABCDEFGHIJKLMNOPQRSTUVWXYZ 0 1
class-lowerCase abcdefghijklmnopqrstuvwxyz 0 1
class-digit 0123456789 0 1
class-special <>,?;.:/!§ù%*µ^¨$£²&é~"#'{([-|è`_\ç^à@)]°=}+ 0 1

Thank you.

**Comment by davidcoutadeur** [comment]
Is cn=admin,dc=user,dc=test,dc=com your Manager account? The one declared in your openldap configuration as managerDN?

**Comment by ahmad-zul** [comment]
I am quite new to openldap / ldap stuff, so I am not sure about managerDN. However cn=admin,dc=user,dc=test,dc=com is my openldap admin user. It is not the same as config admin.

**Comment by davidcoutadeur** [comment]
If it is your openldap super-admin user (ie the user declared in your database configuration as managerDN or olcManagerDN), then the behaviour is quite normal.
The superadmin user bypass the passord policy and ppm.

**Comment by ahmad-zul** [comment]
This is the admin user from my ldapsearch :

\# admin, user.test.com
dn: cn=admin,dc=user,dc=test,dc=com
objectClass: simpleSecurityObject
objectClass: organizationalRole
cn: admin
description: LDAP administrator
userPassword:: e1NTSEF9SUdFbFZzQnFPZ0ZqQTJZdmdVSEV6cTcwNFZTc0owZks=

Is this consider as superadmin? Because I don't see any managerDN or olcManagerDN. Sorry I am a bit noob. 

Thanks

**Comment by davidcoutadeur** [comment]
Your elements can't help to determine if your account "cn=admin,dc=user,dc=test,dc=com" is the superadmin.
As told before, the only way to do this is to look in your database configuration the value of rootDN parameter (if you use slapd.conf configuration mode) or olcRootDN (if you use cn=config configuration mode)
This is not really the good place to discuss about it, I suggest you read OpenLDAP manual: https://www.openldap.org/doc/admin24/slapdconfig.html or use OpenLDAP mailing list
Anyway, the issue does not reflect a bug and so I am closing it.
