### ISSUE TITLE
ppm.so stop/kill slapd

### ISSUE THREAD

**Issue by piengeng** [ltb-project/ppm#33]
scenario, 
on ldap server:
installed slapd in ubuntu 20.04 via `apt install slapd -t jammy` openldap v2.5.11 

missing ppm.so on ldap server, so

on development laptop:
clone openldap v2.5.11 source, attempt to make/build ppm.so , then move ppm.so to ldap server /usr/lib/ldap/ppm.so, tried `ldappasswd` https://pastebin.com/5bersXUc is the output of `journalctl -u slapd -f`

**Comment by piengeng** [comment]
my bad, i compiled ppm on openldap v2.6.1 and expect v2.5.11 to work, compiling on the matching version doesn't kill/stop slapd.

**Comment by coudot** [comment]
@piengeng note that ppm is provided in contrib/ of OpenLDAP sources since 2.5

https://git.openldap.org/openldap/openldap/-/tree/master/contrib/slapd-modules/ppm

**Comment by piengeng** [comment]
@coudot thanks. btw, how do i undefine DEBUG in Makefile? I only know i must `#undef DEBUG` within ppm.h manually.

also, `/var/cache/cracklib/` just cannot be seen by slapd, but other dir already exists with slapd binary/files seems to work.

**Comment by davidcoutadeur** [comment]
You can just try to remove it in `Makefile`:
```
DEFS = -DDEBUG $(CRACKDEF)
```

For `/var/cache/cracklib/`, maybe it's a matter of permissions? Also, please take care that `/var/cache/cracklib/cracklib_dict` is not the directory, but the directory+filename-prefix of the dictionary you want to use.

**Comment by piengeng** [comment]
@davidcoutadeur thanks for the tip. haven't read/study c code for too long a time. :)

yeah, i'm aware about the 3 file extensions of cracklib_dict, i've even move these 3 files to /tmp and chmod 777 on these files, still, it says `ppm: Error while reading /tmp/cracklib_dict.hwm file` it's been driving me nuts, then I remember about the ppm.so, as I have also move ppm.so to where all slapd's *.so lives. perhaps it's just how ubuntu package it. The files are really there and really world-readable, didn't know linux could be configured to limit file/directory access (just my guess)

Anyway, thanks for moving this ppm into openldap. was trying out openldap with ubuntu focal/lts, it's still at v2.4.xx! cannot use ppm at all. that's why trying to figure this thing out.

**Comment by piengeng** [comment]
> @piengeng note that ppm is provided in contrib/ of OpenLDAP sources since 2.5
> 
> https://git.openldap.org/openldap/openldap/-/tree/master/contrib/slapd-modules/ppm

@davidcoutadeur slapd-modules/ppm is meant to be manually compiled and no binary is provided right? how to cross-compile this ppm.so? i can't seems to figure out how to compile this to arm6/7 ... would you please advice?

**Comment by davidcoutadeur** [comment]
@piengeng As far as I know, debian and red-hat packages do not provide ppm for now. (it may change in the future)
However, you can give `OpenLDAP-LTB packages` a try: https://ltb-project.org/documentation/
Please don't use github issues for questions. There is the mailing list for that: https://ltb-project.org/contact.html
