### ISSUE TITLE
Upgrading from v1.4 to v1.6

### ISSUE THREAD

**Issue by davama** [ltb-project/ppm#8]
Hello,

We are trying to upgrade from v1.4 using Centos7 openldap repo rpm but cannot upgrade/install v1.6. 
This is the procedure we did for v1.4 which still passes:

```
#download openldap source
yumdownloader --source openldap
#Extract to build directory
mkdir openldapsrc
cd openldapsrc
rpm2cpio ../openldap-2.4.40-13.el7.src.rpm  | cpio -idmv
tar -xvzf openldap-2.4.40.tgz
#Prepare openldap source header files:
cd openldap-2.4.40
./configure && make depend
#Get PPM 1.4 source:
wget https://github.com/davidcoutadeur/ppm/archive/1.4.zip -O ppm_1_4.zip
#	Extract to openldap-2.4.40/contrib/slapd-modules
cd contrib/slapd-modules
unzip ../../ppm_1_4.zip
#Compile PPM module:
cd ppm-1.4
make clean
make ppm LDAP_INC="-I../../../include -I../../../servers/slapd" CONFIG=/etc/openldap/ppm.conf LIBDIR=/usr/lib64/openldap
make install CONFIG=/etc/openldap/ppm.conf LIBDIR=/usr/lib64/openldap
```

v1.6 fails in the second to last step with this output
```
rm -f ppm.o ppm.so ppm.lo ppm_test
rm -f -r .libs
gcc -g -O2 -Wall -fpic -DCONFIG_FILE="\"/etc/openldap/ppm.conf\"" -DDEBUG -c -I../../../include -I../../../servers/slapd -DCRACKLIB ppm.c
ppm.c:17:66: fatal error: crack.h: No such file or directory
 #include "crack.h"              // use cracklib to check password
                                                                  ^
compilation terminated.
make: *** [ppm.o] Error 1
```

Im assuming it's something similar to #7  but not sure where to start...
any input is appreciated.

thanks,
dave

**Comment by coudot** [comment]
Hi @davama did you install cracklib devel package?

**Comment by davidcoutadeur** [comment]
Hi, you need to install cracklib header files if you compile ppm from sources

**Comment by davidcoutadeur** [comment]
@coudot is too fast...

**Comment by davama** [comment]
@coudot @davidcoutadeur  you both are fast!
Let me try cracklib-dev

```
yum list installed | grep crack
cracklib.x86_64                  2.9.0-11.el7                   @anaconda       
cracklib-dicts.x86_64            2.9.0-11.el7                   @anaconda   
```

**Comment by davama** [comment]
Ok, it got me closer...i think. Mind you i was shaking with excitement when second to last command passed (hopes were high) but failed in very last one...
`make install CONFIG=/etc/openldap/ppm.conf LIBDIR=/usr/lib64/openldap`

output:
```
rm -f ppm.o ppm.so ppm.lo ppm_test
rm -f -r .libs
gcc -g -O2 -Wall -fpic -DCONFIG_FILE="\"/etc/openldap/ppm.conf\"" -DDEBUG -c -I../include -I../servers/slapd -DCRACKLIB ppm.c
ppm.c:11:22: fatal error: portable.h: No such file or directory
 #include <portable.h>
                      ^
compilation terminated.
make: *** [ppm.o] Error 1
```

thank you for the support!

**Comment by coudot** [comment]
portable.h is shipped by OpenLDAP, but you need a ./configure in OpenLDAP sources to get it.

See also https://lists.ltb-project.org/pipermail/ltb-users/2009-December/000011.html

**Comment by davama** [comment]
@coudot  thank you for the input that's brought me closer i believe.

Ok, i've change my procedure a bit since portable.h is provided but $(LDAP_INC) wasnt being respected...

```
#Prepare openldap source header files:
cd openldap-2.4.40
./configure && make depend
#Get PPM 1.6 source:
wget https://github.com/ltb-project/ppm/archive/v1.6.zip -O ppm_1_6.zip
#	Extract
unzip ppm_1_6.zip
#Compile PPM module:
cd ppm-1.6
make clean
make CONFIG=/etc/openldap/ppm.conf LIBDIR=/usr/lib64/openldap
make install CONFIG=/etc/openldap/ppm.conf LIBDIR=/usr/lib64/openldap
```
This is the output from last command, i do not see `cp -f ppm.conf /etc/openldap/ppm.conf
`:
```
rm -f ppm.o ppm.so ppm.lo ppm_test
rm -f -r .libs
gcc -g -O2 -Wall -fpic -DCONFIG_FILE="\"/etc/openldap/ppm.conf\"" -DDEBUG -c -I../include -I../servers/slapd -DCRACKLIB ppm.c
gcc -I../include -I../servers/slapd -shared -o ppm.so ppm.o
cp -f ppm.so /usr/lib64/openldap
cp -f ppm_test /usr/lib64/openldap
cp: cannot stat ‘ppm_test’: No such file or directory
make: *** [install] Error 1
```

**Comment by coudot** [comment]
Well you only compile ppm.c. You also need to compile ppm_test.c if you want to have the ppm_test binary.

**Comment by davidcoutadeur** [comment]
ppm_test should have been built with "make" target, but it seems it is not present. Check that there is no error at the "make" step.

**Comment by davama** [comment]
> ppm_test should have been built with "make" target, but it seems it is not present. Check that there is no error at the "make" step.

yes, it's created on `make`. really what im looking for is `/etc/openldap/ppm.conf` which is doesnt exist.

how i compile ppm from source:
```
[root@datacom-test-ecr-server ppm-1.6]# make clean
rm -f ppm.o ppm.so ppm.lo ppm_test
rm -f -r .libs
[root@datacom-test-ecr-server ppm-1.6]# ls
INSTALL  LICENSE  Makefile  ppm.c  ppm.conf  ppm.h  ppm_test.c  README.md  unit_tests.sh
[root@datacom-test-ecr-server ppm-1.6]# 
[root@datacom-test-ecr-server ppm-1.6]# 
[root@datacom-test-ecr-server ppm-1.6]# make CONFIG=/etc/openldap/ppm.conf LIBDIR=/usr/lib64/openldap
rm -f ppm.o ppm.so ppm.lo ppm_test
rm -f -r .libs
gcc -g -O2 -Wall -fpic -DCONFIG_FILE="\"/etc/openldap/ppm.conf\"" -DDEBUG -c -I../include -I../servers/slapd -DCRACKLIB ppm.c
gcc -I../include -I../servers/slapd -shared -o ppm.so ppm.o
gcc -I../include -I../servers/slapd -L../libraries/liblber/.libs -L../libraries/libldap_r/.libs -lldap_r -llber -lcrack ppm.so -o ppm_test ppm_test.c 
[root@datacom-test-ecr-server ppm-1.6]# 
[root@datacom-test-ecr-server ppm-1.6]# ls
INSTALL  LICENSE  Makefile  ppm.c  ppm.conf  ppm.h  ppm.o  ppm.so  ppm_test  ppm_test.c  README.md  unit_tests.sh
[root@datacom-test-ecr-server ppm-1.6]# make install CONFIG=/etc/openldap/ppm.conf LIBDIR=/usr/lib64/openldap
rm -f ppm.o ppm.so ppm.lo ppm_test
rm -f -r .libs
gcc -g -O2 -Wall -fpic -DCONFIG_FILE="\"/etc/openldap/ppm.conf\"" -DDEBUG -c -I../include -I../servers/slapd -DCRACKLIB ppm.c
gcc -I../include -I../servers/slapd -shared -o ppm.so ppm.o
cp -f ppm.so /usr/lib64/openldap
cp -f ppm_test /usr/lib64/openldap
cp: cannot stat ‘ppm_test’: No such file or directory
make: *** [install] Error 1
```

thank you again for the support

**Comment by coudot** [comment]
@davidcoutadeur Maybe there is a problem in Makefile. The install target should be:
````
install: ppm ppm_test
````
Instead of:
````
install: ppm
````

**Comment by davama** [comment]
@coudot  that was it!

```
vi Makefile # did my changes
[root@datacom-test-ecr-server ppm-1.6]# make clean
rm -f ppm.o ppm.so ppm.lo ppm_test
rm -f -r .libs
[root@datacom-test-ecr-server ppm-1.6]# make CONFIG=/etc/openldap/ppm.conf LIBDIR=/usr/lib64/openldap
rm -f ppm.o ppm.so ppm.lo ppm_test
rm -f -r .libs
gcc -g -O2 -Wall -fpic -DCONFIG_FILE="\"/etc/openldap/ppm.conf\"" -DDEBUG -c -I../include -I../servers/slapd -DCRACKLIB ppm.c
gcc -I../include -I../servers/slapd -shared -o ppm.so ppm.o
gcc -I../include -I../servers/slapd -L../libraries/liblber/.libs -L../libraries/libldap_r/.libs -lldap_r -llber -lcrack ppm.so -o ppm_test ppm_test.c 
[root@datacom-test-ecr-server ppm-1.6]# make install CONFIG=/etc/openldap/ppm.conf LIBDIR=/usr/lib64/openldap
rm -f ppm.o ppm.so ppm.lo ppm_test
rm -f -r .libs
gcc -g -O2 -Wall -fpic -DCONFIG_FILE="\"/etc/openldap/ppm.conf\"" -DDEBUG -c -I../include -I../servers/slapd -DCRACKLIB ppm.c
gcc -I../include -I../servers/slapd -shared -o ppm.so ppm.o
gcc -I../include -I../servers/slapd -L../libraries/liblber/.libs -L../libraries/libldap_r/.libs -lldap_r -llber -lcrack ppm.so -o ppm_test ppm_test.c 
cp -f ppm.so /usr/lib64/openldap
cp -f ppm_test /usr/lib64/openldap
cp -f ppm.conf /etc/openldap/ppm.conf
```

I can submit a PR if you want

**Comment by coudot** [comment]
I let @davidcoutadeur decide how to fix this issue. Thanks for the feedback!

**Comment by davama** [comment]
Sounds good! 
Thank you both for your support and patience!!
Closing

**Comment by davidcoutadeur** [comment]
Indeed, there seem to be a problem in the Makefile:
I don't remember why there is a:
```
ppm: clean ppm.o
```
install calls ppm, which call clean,and clean deletes ppm_test
This is not a good idea.

@davama  I suggest you delete the clean in the quoted line, it should solve all your problems.
Else you won't have the test programs included.

**Comment by davama** [comment]
>@davama I suggest you delete the clean in the quoted line, it should solve all your problems.
Else you won't have the test programs included.

That looks like a more elegant solution:

```
[root@datacom-test-ecr-server ppm-1.6]# make clean
rm -f ppm.o ppm.so ppm.lo ppm_test
rm -f -r .libs
[root@datacom-test-ecr-server ppm-1.6]# make CONFIG=/etc/openldap/ppm.conf LIBDIR=/usr/lib64/openldap
gcc -g -O2 -Wall -fpic -DCONFIG_FILE="\"/etc/openldap/ppm.conf\"" -DDEBUG -c -I../include -I../servers/slapd -DCRACKLIB ppm.c
gcc -I../include -I../servers/slapd -shared -o ppm.so ppm.o
gcc -I../include -I../servers/slapd -L../libraries/liblber/.libs -L../libraries/libldap_r/.libs -lldap_r -llber -lcrack ppm.so -o ppm_test ppm_test.c 
[root@datacom-test-ecr-server ppm-1.6]# make install CONFIG=/etc/openldap/ppm.conf LIBDIR=/usr/lib64/openldap
gcc -I../include -I../servers/slapd -shared -o ppm.so ppm.o
cp -f ppm.so /usr/lib64/openldap
cp -f ppm_test /usr/lib64/openldap
cp -f ppm.conf /etc/openldap/ppm.conf
```

**Comment by davidcoutadeur** [comment]
I am sorry, I have answered too fastly and didn't take time to think enough about it.

> I suggest you delete the clean in the quoted line, it should solve all your problems.
> Else you won't have the test programs included.

@davama  Actually I have suggested you do this as a quick workaround, for you project to compile.

> Maybe there is a problem in Makefile

Yes, this bug wasn't detected because in ltb rpm and deb packages the install phase is never called. Files are moved one by one.

> I don't remember why there is a:
> ppm: clean ppm.o

I suppose it's because it was considered a more secured solution to rebuild each time starting from scratch.
However, it's "make" job to detect modifications and build only changed files. Maybe we can trust it to do this job most of the time. At least for handmade compilation. And then for automatic compilation we can ensure everything is fine by a "make clean" before make. (for debian and rpm ltb packages for example)
I can also add phony target to improve the makefile.

@coudot: is it ok for you?

@coudot : I have also noticed a needed update in openldap-ltb.spec - line 76, 139):
`# Sources available on https://github.com/davidcoutadeur/ppm`
s/davidcoutadeur/ltb-project/

**Comment by coudot** [comment]
Spec file updated: https://github.com/ltb-project/openldap-rpm/commit/b21b745fed03117912695f81a19c7e47c5ae08d9

In DEB and RPM packaging, we are using the ppm source archive, so make clean should not be mandatory as no compilation should have been made in the source archive. We can plan to use the make install target in DEB and RPM too.

**Comment by davidcoutadeur** [comment]
@coudot I realized the parameters used in Makefile should be cleaned a little bit... And also made more generic...
However, this will make a rupture in Makefile default behaviour.
The LDAP_LIBS and LDAP_INC should not be used any more (but you can still do it), and a new variable OLDAP_SOURCES must be used to point to openldap source path. By default, it will point to OpenLDAP as if ppm directory was put in contrib/slapd-modules, as stated in INSTALL file a long time ago.
In LTB packages, ppm directory is supposed to be in current directory, thus OLDAP_SOURCES argument should be added in the future.
Is it ok for you?

**Comment by coudot** [comment]
Yes, please open new issues in openldap-deb and openldap-rpm project so we remember to update packaging for ppm 1.7

**Comment by davidcoutadeur** [comment]
Improvements done in 3fcd0e4
New issues opened:
https://github.com/ltb-project/openldap-rpm/issues/13
https://github.com/ltb-project/openldap-deb/issues/9

I suggest to close this issue.

**Comment by coudot** [comment]
Thanks. Issue is already closed.
